# Generated by Django 5.2.4 on 2025-11-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_bookimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["availability_status", "title"]},
        ),
    ]
